package interfaceGraphique;

import blockchain.Blockchain;

@SuppressWarnings("serial")
public class AffichageBlockchain extends javax.swing.JFrame implements Runnable {
	Blockchain blockchain;
	
    /**
     * Creates new form affichageBlockchain
     */
    public AffichageBlockchain(Blockchain blockchain) {
        initComponents();
        this.blockchain = blockchain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principale = new javax.swing.JPanel();
        jPanel_titre = new javax.swing.JPanel();
        jLabel_titre = new javax.swing.JLabel();
        jScrollPane_blockChain = new javax.swing.JScrollPane();
        jTextArea_blockChain = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 50));

        jPanel_principale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel_titre.setBackground(new java.awt.Color(27, 27, 27));

        jLabel_titre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_titre.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titre.setText("Blockchain:");

        javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
        jPanel_titre.setLayout(jPanel_titreLayout);
        jPanel_titreLayout.setHorizontalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        jPanel_titreLayout.setVerticalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_blockChain.setColumns(20);
        jTextArea_blockChain.setRows(5);
        jScrollPane_blockChain.setViewportView(jTextArea_blockChain);
        jTextArea_blockChain.setEditable(false);

        javax.swing.GroupLayout jPanel_principaleLayout = new javax.swing.GroupLayout(jPanel_principale);
        jPanel_principale.setLayout(jPanel_principaleLayout);
        jPanel_principaleLayout.setHorizontalGroup(
            jPanel_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_principaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_blockChain)
                .addContainerGap())
        );
        jPanel_principaleLayout.setVerticalGroup(
            jPanel_principaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principaleLayout.createSequentialGroup()
                .addComponent(jPanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_blockChain, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public void run() {
         this.setVisible(true);
         jTextArea_blockChain.append(blockchain.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_titre;
    private javax.swing.JPanel jPanel_principale;
    private javax.swing.JPanel jPanel_titre;
    private javax.swing.JScrollPane jScrollPane_blockChain;
    private javax.swing.JTextArea jTextArea_blockChain;
    // End of variables declaration//GEN-END:variables
}
