package interfaceGraphique;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
@SuppressWarnings("serial")
public class AffichagePrincipal extends javax.swing.JFrame {

    /** Creates new form fenetre */
    public AffichagePrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titre = new javax.swing.JPanel();
        jLabel_titre = new javax.swing.JLabel();
        jPanel_principal = new javax.swing.JPanel();
        jLabel_sousTitre = new javax.swing.JLabel();
        jPanel_option = new javax.swing.JPanel();
        jLabel_nbBlock = new javax.swing.JLabel();
        jLabel_nbUtilisateur = new javax.swing.JLabel();
        jLabel_dificulté = new javax.swing.JLabel();
        jTextField_nbBlock = new javax.swing.JTextField();
        jTextField_nbUtilisateur = new javax.swing.JTextField();
        jTextField_dificulte = new javax.swing.JTextField();
        jButton_lancerSimulation = new javax.swing.JButton();
        jLabe_ou = new javax.swing.JLabel();
        jButton_chargerJson = new javax.swing.JButton();
        jPanel_default = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 38, 61));
        setForeground(new java.awt.Color(255, 0, 102));
        setLocation(new java.awt.Point(200, 100));

        jPanel_titre.setOpaque(false);
        jPanel_titre.setPreferredSize(new java.awt.Dimension(10, 57));

        jLabel_titre.setBackground(new java.awt.Color(24, 24, 24));
        jLabel_titre.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_titre.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titre.setText("BONOBO");
        jLabel_titre.setFocusTraversalPolicyProvider(true);
        jLabel_titre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel_titre.setOpaque(true);

        javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
        jPanel_titre.setLayout(jPanel_titreLayout);
        jPanel_titreLayout.setHorizontalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_titreLayout.setVerticalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_principal.setOpaque(false);

        jLabel_sousTitre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_sousTitre.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_sousTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sousTitre.setText("Choisir les paramètre de la simulation: ");

        jPanel_option.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_nbBlock.setBackground(new java.awt.Color(203, 203, 203));
        jLabel_nbBlock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_nbBlock.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_nbBlock.setText("Nombre de block:");

        jLabel_nbUtilisateur.setBackground(new java.awt.Color(203, 203, 203));
        jLabel_nbUtilisateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_nbUtilisateur.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_nbUtilisateur.setText("Nombre d'utilisateur:");

        jLabel_dificulté.setBackground(new java.awt.Color(203, 203, 203));
        jLabel_dificulté.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_dificulté.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_dificulté.setText("Dificulté:");

        jTextField_nbBlock.setCaretColor(new java.awt.Color(201, 201, 201));
        jTextField_nbBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbBlockActionPerformed(evt);
            }
        });

        jTextField_nbUtilisateur.setCaretColor(new java.awt.Color(201, 201, 201));
        jTextField_nbUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbUtilisateurActionPerformed(evt);
            }
        });

        jTextField_dificulte.setCaretColor(new java.awt.Color(201, 201, 201));
        jTextField_dificulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dificulteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_optionLayout = new javax.swing.GroupLayout(jPanel_option);
        jPanel_option.setLayout(jPanel_optionLayout);
        jPanel_optionLayout.setHorizontalGroup(
            jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_nbUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_dificulté, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_nbBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_nbBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nbUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_dificulte, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_optionLayout.setVerticalGroup(
            jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nbBlock)
                    .addComponent(jTextField_nbBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nbUtilisateur)
                    .addComponent(jTextField_nbUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dificulté)
                    .addComponent(jTextField_dificulte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jButton_lancerSimulation.setBackground(new java.awt.Color(255, 206, 0));
        jButton_lancerSimulation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_lancerSimulation.setForeground(new java.awt.Color(64, 64, 64));
        jButton_lancerSimulation.setText("Lancer la simulation");
        jButton_lancerSimulation.setBorderPainted(false);
        jButton_lancerSimulation.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton_lancerSimulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_lancerSimulationMouseClicked(evt);
            }
        });
        jButton_lancerSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lancerSimulationActionPerformed(evt);
            }
        });

        jLabe_ou.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabe_ou.setForeground(new java.awt.Color(64, 64, 64));
        jLabe_ou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabe_ou.setText("ou");

        jButton_chargerJson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_chargerJson.setForeground(new java.awt.Color(64, 64, 64));
        jButton_chargerJson.setText("Charger un fichier Json");
        jButton_chargerJson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_chargerJsonMouseClicked(evt);
            }
        });
        jButton_chargerJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chargerJsonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sousTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_option, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_lancerSimulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabe_ou, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_chargerJson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel_sousTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_lancerSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabe_ou)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_chargerJson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel_default.setBackground(new java.awt.Color(244, 244, 244));

        javax.swing.GroupLayout jPanel_defaultLayout = new javax.swing.GroupLayout(jPanel_default);
        jPanel_default.setLayout(jPanel_defaultLayout);
        jPanel_defaultLayout.setHorizontalGroup(
            jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel_defaultLayout.setVerticalGroup(
            jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_default, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_default, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nbBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nbBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nbBlockActionPerformed

    private void jTextField_nbUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nbUtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nbUtilisateurActionPerformed

    private void jTextField_dificulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dificulteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dificulteActionPerformed

    private void jButton_lancerSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lancerSimulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_lancerSimulationActionPerformed

    private void jButton_lancerSimulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_lancerSimulationMouseClicked
        
        int nbBlock;
        int nbUser;
        int dificulte;
        
        try {
            nbBlock = Integer.parseInt(jTextField_nbBlock.getText());
            nbUser = Integer.parseInt(jTextField_nbUtilisateur.getText());
            dificulte = Integer.parseInt(jTextField_dificulte.getText());

            if (dificulte <1 || nbUser <2 || nbBlock < 1){
                JOptionPane.showMessageDialog(this, "dificulte <=1 \n nbUser <= 2 \n nbBlock <= 1");
            }
            else{
                Runnable e = new AffichageSimulation(nbBlock,nbUser,dificulte);
                new Thread(e).start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "veullez rentrer des donnés valide\n");
        }
    }//GEN-LAST:event_jButton_lancerSimulationMouseClicked

    private void jButton_chargerJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chargerJsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_chargerJsonActionPerformed

    private void jButton_chargerJsonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_chargerJsonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_chargerJsonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichagePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichagePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichagePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichagePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichagePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_chargerJson;
    private javax.swing.JButton jButton_lancerSimulation;
    private javax.swing.JLabel jLabe_ou;
    private javax.swing.JLabel jLabel_dificulté;
    private javax.swing.JLabel jLabel_nbBlock;
    private javax.swing.JLabel jLabel_nbUtilisateur;
    private javax.swing.JLabel jLabel_sousTitre;
    private javax.swing.JLabel jLabel_titre;
    private javax.swing.JPanel jPanel_default;
    private javax.swing.JPanel jPanel_option;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JPanel jPanel_titre;
    private javax.swing.JTextField jTextField_dificulte;
    private javax.swing.JTextField jTextField_nbBlock;
    private javax.swing.JTextField jTextField_nbUtilisateur;
    // End of variables declaration//GEN-END:variables

}