package interfaceGraphique;


import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import blockchain.Blockchain;
import scenario.Scenario;
import transactionAleatoire.Aleatoire;
import transactionAleatoire.transactionAleatoire;
import user.Coinbase;
import user.Creator;
import user.User;

/**
 *
 * @author kevin
 */
@SuppressWarnings("serial")
public class AffichageSimulation extends javax.swing.JFrame implements Runnable {
    private int nbBlock;
    private int nbUser;
    private int difficulte;
    // création list d'utilisateur 
	List<User> listUser;
	Blockchain blockchain;
    /**
     * Creates new form simulation
     */

    public AffichageSimulation(int nbBlock,int nbUser, int difficulte) {
        initComponents();
        this.nbBlock = nbBlock;
        this.nbUser = nbUser;
        this.difficulte = difficulte;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titre = new javax.swing.JPanel();
        jLabel_titre = new javax.swing.JLabel();
        jLabel_nbBlock = new javax.swing.JLabel();
        jLabel_nbUtilisateur = new javax.swing.JLabel();
        jLabel_difficulte = new javax.swing.JLabel();
        jPanel_option = new javax.swing.JPanel();
        jButton_json = new javax.swing.JButton();
        jButton_afficherBlockChaine = new javax.swing.JButton();
        jTextField_afficherBlock = new javax.swing.JTextField();
        jButton_ok = new javax.swing.JButton();
        jLabel_afficherBlock = new javax.swing.JLabel();
        jButton_verif = new javax.swing.JButton();
        jPanel_utilisateur = new javax.swing.JPanel();
        jLabel_utilisateur = new javax.swing.JLabel();
        jScrollPane_utilisateur = new javax.swing.JScrollPane();
        jTextArea_utilisateur = new javax.swing.JTextArea();
        jPanel_minage = new javax.swing.JPanel();
        jLabel_minage = new javax.swing.JLabel();
        jScrollPane_minage = new javax.swing.JScrollPane();
        jTextArea_minage = new javax.swing.JTextArea();
        jPanel_transaction = new javax.swing.JPanel();
        jLabel_transaction = new javax.swing.JLabel();
        jScrollPane_transaction = new javax.swing.JScrollPane();
        jTextArea_transaction = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));

        jPanel_titre.setBackground(new java.awt.Color(27, 27, 27));

        jLabel_titre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_titre.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titre.setText("Simulation en cours...");

        jLabel_nbBlock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nbBlock.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_nbBlock.setText("Nombre de block à miner:");

        jLabel_nbUtilisateur.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nbUtilisateur.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_nbUtilisateur.setText("Nombre d'utilisateurs:");

        jLabel_difficulte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_difficulte.setForeground(new java.awt.Color(255, 206, 0));
        jLabel_difficulte.setText("test");

        javax.swing.GroupLayout jPanel_titreLayout = new javax.swing.GroupLayout(jPanel_titre);
        jPanel_titre.setLayout(jPanel_titreLayout);
        jPanel_titreLayout.setHorizontalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titreLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel_difficulte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_nbUtilisateur)
                .addGap(249, 249, 249)
                .addComponent(jLabel_nbBlock)
                .addGap(125, 125, 125))
        );
        jPanel_titreLayout.setVerticalGroup(
            jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_difficulte)
                    .addComponent(jLabel_nbUtilisateur)
                    .addComponent(jLabel_nbBlock))
                .addGap(12, 12, 12))
        );

        jButton_json.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_json.setForeground(new java.awt.Color(64, 64, 64));
        jButton_json.setText("Sauvgarder la Blockchain en Json");
        jButton_json.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_jsonMouseClicked(evt);
            }
        });
        jButton_json.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_jsonActionPerformed(evt);
            }
        });

        jButton_afficherBlockChaine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_afficherBlockChaine.setForeground(new java.awt.Color(64, 64, 64));
        jButton_afficherBlockChaine.setText("afficher la blockchain");
        jButton_afficherBlockChaine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_afficherBlockChaineMouseClicked(evt);
            }
        });
        jButton_afficherBlockChaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_afficherBlockChaineActionPerformed(evt);
            }
        });

        jTextField_afficherBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_afficherBlockActionPerformed(evt);
            }
        });

        jButton_ok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ok.setForeground(new java.awt.Color(64, 64, 64));
        jButton_ok.setText("OK");
        jButton_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_okMouseClicked(evt);
            }
        });
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jLabel_afficherBlock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_afficherBlock.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_afficherBlock.setText("Afficher le block:");

        jButton_verif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_verif.setForeground(new java.awt.Color(64, 64, 64));
        jButton_verif.setText("vérifier l’intégrité de la blockchain");
        jButton_verif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_verifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_optionLayout = new javax.swing.GroupLayout(jPanel_option);
        jPanel_option.setLayout(jPanel_optionLayout);
        jPanel_optionLayout.setHorizontalGroup(
            jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton_verif)
                .addGap(41, 41, 41)
                .addComponent(jButton_json)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_afficherBlockChaine)
                .addGap(42, 42, 42)
                .addComponent(jLabel_afficherBlock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_afficherBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ok)
                .addGap(27, 27, 27))
        );
        jPanel_optionLayout.setVerticalGroup(
            jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_optionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_afficherBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_afficherBlock)
                        .addComponent(jButton_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_verif)
                        .addComponent(jButton_json, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_afficherBlockChaine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel_utilisateur.setOpaque(false);

        jLabel_utilisateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_utilisateur.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_utilisateur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_utilisateur.setText("Liste Utilisateurs");

        jTextArea_utilisateur.setColumns(20);
        jTextArea_utilisateur.setRows(5);
        jScrollPane_utilisateur.setViewportView(jTextArea_utilisateur);
        jTextArea_utilisateur.setEditable(false);

        javax.swing.GroupLayout jPanel_utilisateurLayout = new javax.swing.GroupLayout(jPanel_utilisateur);
        jPanel_utilisateur.setLayout(jPanel_utilisateurLayout);
        jPanel_utilisateurLayout.setHorizontalGroup(
            jPanel_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanel_utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_utilisateur)
                .addContainerGap())
        );
        jPanel_utilisateurLayout.setVerticalGroup(
            jPanel_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_utilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_utilisateur)
                .addContainerGap())
        );

        jPanel_minage.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel_minage.setOpaque(false);

        jLabel_minage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_minage.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_minage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minage.setText("Trace du minage");

        jTextArea_minage.setColumns(20);
        jTextArea_minage.setRows(5);
        jScrollPane_minage.setViewportView(jTextArea_minage);
        jTextArea_minage.setEditable(false);

        javax.swing.GroupLayout jPanel_minageLayout = new javax.swing.GroupLayout(jPanel_minage);
        jPanel_minage.setLayout(jPanel_minageLayout);
        jPanel_minageLayout.setHorizontalGroup(
            jPanel_minageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_minage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_minageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_minage)
                .addContainerGap())
        );
        jPanel_minageLayout.setVerticalGroup(
            jPanel_minageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_minageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_minage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_minage, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_transaction.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel_transaction.setOpaque(false);

        jLabel_transaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_transaction.setForeground(new java.awt.Color(64, 64, 64));
        jLabel_transaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_transaction.setText("Liste de transaction Global");

        jTextArea_transaction.setColumns(20);
        jTextArea_transaction.setRows(5);
        jScrollPane_transaction.setViewportView(jTextArea_transaction);
        jTextArea_transaction.setEditable(false);

        javax.swing.GroupLayout jPanel_transactionLayout = new javax.swing.GroupLayout(jPanel_transaction);
        jPanel_transaction.setLayout(jPanel_transactionLayout);
        jPanel_transactionLayout.setHorizontalGroup(
            jPanel_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_transactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_transaction)
                .addContainerGap())
        );
        jPanel_transactionLayout.setVerticalGroup(
            jPanel_transactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_transactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_transaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_transaction)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_minage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_option, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_minage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_jsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_jsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_jsonActionPerformed

    private void jButton_afficherBlockChaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_afficherBlockChaineActionPerformed
        Runnable e = new AffichageBlockchain(blockchain);
        new Thread(e).start();
    }//GEN-LAST:event_jButton_afficherBlockChaineActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jTextField_afficherBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_afficherBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_afficherBlockActionPerformed

    private void jButton_verifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_verifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_verifMouseClicked

    private void jButton_jsonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_jsonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_jsonMouseClicked

    private void jButton_afficherBlockChaineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_afficherBlockChaineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_afficherBlockChaineMouseClicked

    private void jButton_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_okMouseClicked
		int num;
        try {
            num = Integer.parseInt(jTextField_afficherBlock.getText());
            JOptionPane.showMessageDialog(this, "cecie est un teste"+difficulte);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "veullez rentrer un donné valide\n");
        }

    }//GEN-LAST:event_jButton_okMouseClicked

    public void run() {
    			
    	this.setVisible(true);
        jLabel_difficulte.setText("Dificulté: "+difficulte);
        jLabel_nbBlock.setText("Nombre de bloc à miner: "+nbBlock);
        jLabel_nbUtilisateur.setText("Nombre d'utilisateur: "+nbUser);
    	
    	// création liste user
    	listUser = new ArrayList<>();
    	
    	// création user Creator
    	Creator creator = new Creator();
    	listUser.add(creator);
    	
    	// création User Coinbase
    	Coinbase coinbase = new Coinbase();				
    	
    	// ajout d'User aléatoire
    	listUser.addAll(Aleatoire.listUserRandom(nbUser));
    	
    	// affichage de la liste utilistaeur
    	for (int i=0 ; i<listUser.size() ; i++)
    		jTextArea_utilisateur.append("user "+i+": "+listUser.get(i).getPrenom()+"\n");
    		
    	// création blockchain
    	blockchain = new Blockchain(difficulte, listUser);
    	
    	// création theard interface
    	UtilsTransac interfaceG = new UtilsTransac(blockchain,jTextArea_transaction, jScrollPane_transaction);
    	interfaceG.start();
    	     	
        Scenario.scenario(difficulte, 
		        		nbBlock, 
		        		nbUser, 
		        		blockchain, 
		        		listUser, 
		        		coinbase, 
		        		creator, 
		        		jTextArea_minage, 
		        		jScrollPane_minage);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_afficherBlockChaine;
    private javax.swing.JButton jButton_json;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JButton jButton_verif;
    private javax.swing.JLabel jLabel_afficherBlock;
    private javax.swing.JLabel jLabel_difficulte;
    private javax.swing.JLabel jLabel_minage;
    private javax.swing.JLabel jLabel_nbBlock;
    private javax.swing.JLabel jLabel_nbUtilisateur;
    private javax.swing.JLabel jLabel_titre;
    private javax.swing.JLabel jLabel_transaction;
    private javax.swing.JLabel jLabel_utilisateur;
    private javax.swing.JPanel jPanel_minage;
    private javax.swing.JPanel jPanel_option;
    private javax.swing.JPanel jPanel_titre;
    private javax.swing.JPanel jPanel_transaction;
    private javax.swing.JPanel jPanel_utilisateur;
    private javax.swing.JScrollPane jScrollPane_minage;
    private javax.swing.JScrollPane jScrollPane_transaction;
    private javax.swing.JScrollPane jScrollPane_utilisateur;
    private javax.swing.JTextArea jTextArea_minage;
    private javax.swing.JTextArea jTextArea_transaction;
    private javax.swing.JTextArea jTextArea_utilisateur;
    private javax.swing.JTextField jTextField_afficherBlock;
    // End of variables declaration//GEN-END:variables
}